// THIS FILE IS AUTO-GENERATED by astro-pagescms
// Source: .pages.yml — do not edit manually, changes will be overwritten on next build

import { file, glob } from 'astro/loaders';
import { z } from 'astro/zod';
import type { SchemaContext } from 'astro:content';
import { defineCollection } from 'astro:content';

// Collections
const pages = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/pages" }),
  schema: ({ image }) =>
    z.object({
  uuid: z.string().uuid().optional(),
  title: z.string().optional(),
  description: z.string().optional(),
  slug: z.string().optional(),
  hideHeaderTrigger: z.boolean().default(false),
  seo: z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  image: image().or(z.string()).optional(),
}).optional(),
  sections: z.array(
z.discriminatedUnion("type", [
z.object({
  type: z.literal("homepageBlock"),
}),
z.object({
  type: z.literal("textBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  body: z.string().optional(),
}),
z.object({
  type: z.literal("stickyHeadingBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  body: z.string().optional(),
}),
z.object({
  type: z.literal("enquiriesBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  lines: z.array(z.object({
  text: z.string().optional(),
  href: z.string().optional(),
})).default([]),
}),
z.object({
  type: z.literal("peopleBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  people: z.array(z.object({
  name: z.string(),
  image: z.object({
  src: image().or(z.string()).optional(),
  alt: z.string().optional(),
}).optional(),
  bio: z.string().optional(),
})).default([]),
}),
])
).default([]),
}),
});
const redirects = defineCollection({
  loader: file("./src/content/redirects.json", {
    parser: (text) => {
      const items = JSON.parse(text) as Array<Record<string, unknown>>;
      return items.map((item, i) => ({ id: String(i), ...item }));
    },
  }),
  schema: z.object({
  from: z.string(),
  to: z.string(),
  status: z.enum(["301", "302"]).default("301"),
}),
});

export const collections = { pages, redirects };
